## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [0]:
import tensorflow as tf

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default

### Collect Data

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('/content/drive/My Drive/Machine Learning/Assignments/Internal/Residency 6 internal assignment/prices.csv')

### Check all columns in the dataset

In [14]:
data.head()

                  date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

### Drop columns `date` and  `symbol`

In [16]:
data = data.drop(["date","symbol"], axis=1)
data.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [18]:
df = data.head(1000)
df.shape

(1000, 5)

In [19]:
df["volume"] = df["volume"]/1000000

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [20]:
df.head()

         open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [0]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
X=df.drop(['volume'],axis=1)
Y=df[['volume']]
X = np.array(X, dtype=float)
Y = np.array(Y, dtype=float)
X_normal = normalize(X)
Xtrain,Xtest,ytrain,ytest=train_test_split(X_normal,Y,test_size=0.3,random_state=1)

#### Convert Training and Test Data to numpy float32 arrays

### Normalize the data
You can use Normalizer from sklearn.preprocessing

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
#Input features
x = tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')

#Normalize the data
#x_n = tf.nn.l2_normalize(x,1)

#Actual Prices
y_ = tf.placeholder(shape=[None,1],dtype=tf.float32, name='y-input')

In [0]:
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

2.Define a function to calculate prediction

In [0]:
y = tf.add(tf.matmul(x,W),b,name='output')

3.Loss (Cost) Function [Mean square error]

In [0]:
loss = tf.reduce_mean(tf.square(y-y_),name='Loss')

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

In [0]:
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [48]:
ytrain.shape

(700, 1)

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [67]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:Xtrain, y_:ytrain})
    
    if epoch % 5 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

('Training loss at step: ', 0, ' is ', 225.87955)
('Training loss at step: ', 5, ' is ', 203.89189)
('Training loss at step: ', 10, ' is ', 197.76788)
('Training loss at step: ', 15, ' is ', 196.0621)
('Training loss at step: ', 20, ' is ', 195.58679)
('Training loss at step: ', 25, ' is ', 195.4542)
('Training loss at step: ', 30, ' is ', 195.4171)
('Training loss at step: ', 35, ' is ', 195.40652)
('Training loss at step: ', 40, ' is ', 195.4034)
('Training loss at step: ', 45, ' is ', 195.40233)
('Training loss at step: ', 50, ' is ', 195.40182)
('Training loss at step: ', 55, ' is ', 195.40144)
('Training loss at step: ', 60, ' is ', 195.40115)
('Training loss at step: ', 65, ' is ', 195.40086)
('Training loss at step: ', 70, ' is ', 195.40057)
('Training loss at step: ', 75, ' is ', 195.40028)
('Training loss at step: ', 80, ' is ', 195.40002)
('Training loss at step: ', 85, ' is ', 195.39975)
('Training loss at step: ', 90, ' is ', 195.39944)
('Training loss at step: ', 95, ' is ', 195.39912)

### Get the shapes and values of W and b

In [69]:
W.shape

TensorShape([Dimension(4), Dimension(1)])

In [87]:
W.eval(sess)

array([[1.2999035],
       [1.445007 ],
       [1.3115764],
       [1.4610407]], dtype=float32)

In [70]:
b.shape

TensorShape([Dimension(1)])

In [88]:
b.eval(sess)

array([2.7608385], dtype=float32)

### Model Prediction on 1st Examples in Test Dataset

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [102]:
Iris = pd.read_csv('/content/drive/My Drive/Machine Learning/Assignments/Internal/Residency 6 internal assignment/11_Iris.csv')
Iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [103]:
Iris = pd.get_dummies(Iris, drop_first=True)
Iris_df = Iris.drop(['Id'], axis=1)
Iris_df.head()

   SepalLengthCm  SepalWidthCm  ...  Species_Iris-versicolor  Species_Iris-virginica
0            5.1           3.5  ...                        0                       0
1            4.9           3.0  ...                        0                       0
2            4.7           3.2  ...                        0                       0
3            4.6           3.1  ...                        0                       0
4            5.0           3.6  ...                        0                       0

[5 rows x 6 columns]

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [0]:
#from sklearn import preprocessing 
#label_encoder = preprocessing.LabelEncoder() 
#Iris['Species']= label_encoder.fit_transform(Iris['Species']) 
#Iris.head()

### Splitting the data into feature set and target set

In [117]:
X=Iris_df.drop(['Species_Iris-versicolor','Species_Iris-virginica'],axis=1)
#Y=Iris['Species_Iris-versicolor','Species_Iris-virginica']
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [118]:
Y = Iris_df[['Species_Iris-versicolor','Species_Iris-virginica']]
Y.head()

   Species_Iris-versicolor  Species_Iris-virginica
0                        0                       0
1                        0                       0
2                        0                       0
3                        0                       0
4                        0                       0

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [0]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(12, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='sigmoid'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

### Model Training

In [122]:
model.fit(X, Y, epochs=10, batch_size=10)

W0721 12:02:07.623294 140466418206592 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py:1250: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0721 12:02:07.674438 140466418206592 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Epoch 1/10
150/150 [==============================] - 0s 3ms/step - loss: 0.5354 - acc: 0.3333
Epoch 2/10
150/150 [==============================] - 0s 164us/step - loss: 0.4863 - acc: 0.3333
Epoch 3/10
150/150 [==============================] - 0s 143us/step - loss: 0.4730 - acc: 0.3333
Epoch 4/10
150/150 [==============================] - 0s 134us/step - loss: 0.4673 - acc: 0.3333
Epoch 5/10
150/150 [==============================] - 0s 144us/step - loss: 0.4646 - acc: 0.3333
Epoch 6/10
150/150 [==============================] - 0s 125us/step - loss: 0.4631 - acc: 0.3333
Epoch 7/10
150/150 [==============================] - 0s 137us/step - loss: 0.4617 - acc: 0.3333
Epoch 8/10
150/150 [==============================] - 0s 157us/step - loss: 0.4610 - acc: 0.3333
Epoch 9/10
150/150 [==============================] - 0s 140us/step - loss: 0.4600 - acc: 0.3333
Epoch 10/10
150/150 [==============================] - 0s 135us/step - loss: 0.4602 - acc: 0.3333

### Model Prediction

In [123]:
scores = model.evaluate(X, Y)
scores[1]*100

150/150 [==============================] - 0s 425us/step

33.33333333333333

### Save the Model

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?